sudo: false
dist: trusty
language: bash

notifications:
  email:
    on_success: never
    on_failure: change

addons:
  apt:
    sources:
      - sourceline: 'ppa:duggan/bats'
    packages:
      - bats

script:
  - bats test
